/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#d5e3fd",
        "on-primary-fixed": "#131b2e",
        "tertiary-fixed": "#6ffbbe",
        "surface-bright": "#f8f9ff",
        "primary-fixed": "#dae2fd",
        "surface-container-highest": "#d3e4fe",
        "inverse-on-surface": "#eaf1ff",
        "on-secondary-fixed-variant": "#3a485c",
        "tertiary": "#000000",
        "surface-variant": "#d3e4fe",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#005236",
        "on-background": "#0b1c30",
        "on-error": "#ffffff",
        "on-primary-container": "#7c839b",
        "primary": "#000000",
        "secondary-fixed-dim": "#b9c7e0",
        "background": "#f8f9ff",
        "surface-tint": "#565e74",
        "error": "#ba1a1a",
        "primary-container": "#131b2e",
        "inverse-primary": "#bec6e0",
        "outline": "#76777d",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#0b1c30",
        "on-secondary-fixed": "#0d1c2f",
        "on-tertiary-container": "#009668",
        "on-surface-variant": "#45464d",
        "surface-dim": "#cbdbf5",
        "inverse-surface": "#213145",
        "primary-fixed-dim": "#bec6e0",
        "surface": "#f8f9ff",
        "tertiary-fixed-dim": "#4edea3",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "secondary-container": "#d5e3fd",
        "surface-container": "#e5eeff",
        "surface-container-low": "#eff4ff",
        "surface-container-high": "#dce9ff",
        "on-tertiary-fixed": "#002113",
        "tertiary-container": "#002113",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#3f465c",
        "on-secondary-container": "#57657b",
        "outline-variant": "#c6c6cd",
        "secondary": "#515f74"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
